[package]
name = "sseer"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = { version = "1.11.0" }
bytes-utils = "0.1.4"
futures-core = "0.3.31"
futures-timer = "3.0.3"
http-body-util = "0.1.3"
memchr = "2.7.6"
pin-project-lite = "0.2.16"
reqwest = { version = "0.13.1", features = [
    "stream",
], default-features = false, optional = true }

[features]
reqwest = ["dep:reqwest"]

[dev-dependencies]
futures = "0.3.31"
tokio = { version = "1.49.0", features = ["full"] }
